export const LOGIN_SUCCES = "LOGIN_SUCCES";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SIGNUP_SUCCES = "SIGNUP_SUCCES";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const SIGNOUT_SUCCES = "SIGNOUT_SUCCES";

export const PHOTO_URL = "PHOTO_URL";

export const MESSAGING_TOKEN = "MESSAGING_TOKEN";

export const SEND_NOTIFICATIONS = "SEND_NOTIFICATIONS";

export const PAGE_LOADING = "PAGE_LOADING";
export const PAGE_LOADED = "PAGE_LOADED";

export const SHOW_NOTIFICATIONS = "SHOW_NOTIFICATIONS";
export const HIDE_NOTIFICATIONS = "HIDE_NOTIFICATIONS";

export const CALL_REFUSED = "CALL_REFUSED";
